version: "3.9"

services:
  global_nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
      - ${PROJECTS_FOLDER}:/var/www
    container_name: global_nginx
    env_file:
      - .env

  global_php_8.2:
    build:
      context: ./php8.2/
    container_name: global_php_8.2
    volumes:
      - ./php8.2/xdebug.ini:/usr/local/etc/php/conf.d/z-xdebug.ini
      - ${PROJECTS_FOLDER}:/var/www
    env_file:
      - .env

  global_php_7.4:
    build:
      context: ./php7.4/
    container_name: global_php_7.4
    volumes:
      - ./php7.4/xdebug.ini:/usr/local/etc/php/conf.d/z-xdebug.ini
      - ${PROJECTS_FOLDER}:/var/www
    env_file:
      - .env

  global_mysql:
    build:
      context: ./mysql/
    container_name: global_mysql
    volumes:
      - ./mysql/data:/user_data
    env_file:
      - .env
    ports:
      - "127.0.0.1:3306:3306"
    restart: always